CREATE TABLE redrock.t_users (
    username character varying(250) NOT NULL,
    password character varying(255),
    emailaddr character varying(150) NOT NULL,
    firstname character varying(255),
    lastname character varying(255),
    address character varying(255),
    address2 character varying(255),
    city character varying(100),
    state character varying(20),
    country character varying(50),
    postalcode character varying(25),
    phonenumber character varying(40),
    extrefid character varying(255),
    hasnotes numeric DEFAULT 0 NOT NULL,
    hasdocuments numeric DEFAULT 0 NOT NULL,
    hasreservedtimes numeric DEFAULT 0 NOT NULL,
    timezone character varying(30),
    locale character varying(10),
    uicode character varying(50),
    title character varying(250),
    passworddate numeric,
    costperhour numeric(18,2),
    hasrecentnotes numeric DEFAULT 0 NOT NULL,
    hasmsgs numeric DEFAULT 0 NOT NULL,
    tmppass character varying(32),
    billrateperhour numeric(18,2),
    lastupdatedate numeric,
    name character varying(512),
    logincount numeric DEFAULT 0 NOT NULL,
    lastlogindate numeric,
    isactive numeric DEFAULT 1 NOT NULL,
    webdavprofile numeric DEFAULT 0 NOT NULL,
    entrydate numeric,
    olv numeric DEFAULT 0 NOT NULL,
    ssokey character varying(64),
    hasapiaccess numeric DEFAULT 1 NOT NULL,
    ssousername character varying(255),
    onlyssoaccess numeric DEFAULT 1 NOT NULL,
    roleavail numeric(18,6),
    registrationtoken character varying(32),
    registrationexpiredate numeric,
    tmppassexpiredate numeric,
    failedloginattempts numeric DEFAULT 0 NOT NULL,
    failedlogindate numeric,
    phoneextension character varying(20),
    mobilephonenumber character varying(40),
    myinfo character varying(2000),
    nextsurveyon numeric,
    persona character varying(50) DEFAULT 'NA'::character varying,
    defaultinterface numeric DEFAULT 0 NOT NULL,
    avatardate numeric,
    statusupdate character varying(4000),
    avatarsize numeric DEFAULT 0,
    avatarx numeric DEFAULT 0,
    avatary numeric DEFAULT 0,
    customerguid character varying(32) NOT NULL,
    companyguid character varying(32),
    guid character varying(32) NOT NULL,
    managerguid character varying(32),
    lastupdatedbyguid character varying(32),
    homegroupguid character varying(32) NOT NULL,
    roleguid character varying(32),
    scheduleguid character varying(32),
    timesheetprofileguid character varying(32),
    resourcepoolguid character varying(32),
    defaulthourtypeguid character varying(32),
    portalprofileguid character varying(32),
    lastenterednoteguid character varying(32),
    lastnoteguid character varying(32),
    categoryguid character varying(32),
    accesslevelguid character varying(32),
    latestupdatenoteguid character varying(32),
    lastwhatsnew numeric,
    hometeamguid character varying(32),
    lastannouncement numeric,
    prefuiguid character varying(32),
    hasprooflicense numeric DEFAULT 0 NOT NULL,
    proofaccountpassword character varying(255),
    layouttemplateguid character varying(32),
    passwordhistory character varying(2000),
    boxrefreshtoken character varying(64),
    googlerefreshtoken character varying(64),
    dropboxtoken character varying(64),
    dropboxtokensecret character varying(64),
    licensetype character varying(1),
    apikey character varying(255),
    enteredbyguid character varying(32),
    installablesrun numeric DEFAULT 0 NOT NULL,
    sharepointrefreshtoken character varying(400),
    webdamrefreshtoken character varying(64),
    workfrontdamrefreshtoken character varying(64),
    nextcustomerfeedbacktype character varying(2) DEFAULT 'SR'::character varying NOT NULL,
    delegationtoguid character varying(32),
    proofhqauthtoken character varying(255),
    apikeycreatedate numeric,
    proofhqusername character varying(64),
    deleted character(1),
    deletiondate timestamp(3) without time zone,
    recycletoken character varying(32),
    proofaccountrole numeric,
    scheduleddeactivationdate numeric,
    lastproofapprovalsync numeric DEFAULT 0,
    receiveemails numeric(1,0) DEFAULT 0 NOT NULL,
    uumuserid character varying(32),
    syncwithuum numeric DEFAULT 0 NOT NULL,
    logtimeindays numeric(1,0) DEFAULT 0 NOT NULL,
    workhoursperday numeric(6,4) DEFAULT 8 NOT NULL,
    hasquicksilver numeric DEFAULT 0 NOT NULL,
    uitemplateguid character varying(32),
    eauthuserguid character varying(64),
    actualdeactivationdate numeric,
    isloginblocked numeric DEFAULT 0 NOT NULL,
    accesslevelguidbackup character varying(32),
    licenseupgradeddate numeric,
    worktime numeric(7,6) DEFAULT 1 NOT NULL
);